### ISSUE TITLE
Allow framework functions to be called without an instance of KoinComponent

### ISSUE THREAD

**Issue by scottsteen** [Ekito/koin#129]
**Is your feature request related to a problem? Please describe.**
I cannot call any of the functions defined in [KoinComponent](https://github.com/Ekito/koin/blob/master/koin-core/src/main/kotlin/org/koin/standalone/KoinComponent.kt) without first implementing the interface.
These functions control the dependency injection, which is core to the framework's functionality.

**Describe the solution you'd like**
The functions defined should not be associated with a class or interface. Kotlin allows functions to be declared standalone, without the necessity of being associated with a type (such as an application's `main` method).

This would also remove the need for the `koin-ktor` project, as these seem to just be the same functionality applied to a ktor `Application`. Also the duplication in `ktor-android` can be removed.

Happy to create a pull request if needed.

**Describe alternatives you've considered**
I've created a Kotlin `object` that implements the `KoinComponent` interface. This allows me to call `inject()` anywhere in my code. this workaround is fine, but I feel Koin would be better with this proposal. 

**Target Koin project**
koin-core (possibly koin-ktor & koin-android)

**Comment by erickok** [comment]
That won't really work on Android as the Context won't be available on your object's `init`.

**Comment by scottsteen** [comment]
I'm not sure what you mean. My proposal is to bypass the need for an object; the object is just my current workaround.

I would like to see the `inject()`, `property()`, `get()`, etc functions declared in KoinComponent to be available without an instance of the interface being required.

So, instead of 
```
inline fun <reified T> KoinComponent.inject(name: String = "") =
kotlin.lazy { (StandAloneContext.koinContext as KoinContext).get<T>(name, emptyParameters()) }
```
We'd have (note that `KoinComponent` is no longer the receiver)
```
inline fun <reified T> inject(name: String = "") =
kotlin.lazy { (StandAloneContext.koinContext as KoinContext).get<T>(name, emptyParameters()) }
```
Meaning the function would just 'belong' to the package.

**Comment by erickok** [comment]
Sure, I agree Koin should not log anything by default. cf #50

**Comment by erickok** [comment]
Right. I actually think the marker interface and neat, but indeed the current 'duplication' in koin-ktor is not super useful. For Android though there is a bit mroe to it (installing an Android logger). I would still agree with you though.

**Comment by arnaudgiuliani** [comment]
Hello,

we have thought about it at the beginning of Koin: inject from everywhere. We refused to do it so, you are hardly linked to the Koin API. It should be a limited case in your code. Koin APIs to retrieve components inject/get are defined in a target Runtime/SDK (Android, Ktor ...).

That's why we consider having a semantic marker, to indicate to this component is hardly linked to the Koin Container: you tag your class as a `KoinComponent` to indicate that you will resolve Koin things from inside this component, and won't be directly created by Koin container, but pulled outside Koin container.

`KoinComponent` also help you fill a gap when the actual Koin project that you are using, is missing an API integration, or your usage is less "standard".

Inject from anywhere it's not our actual recommendation.

**Comment by scottsteen** [comment]
It's your project, so you are obviously in control of the restrictions you wish to impose on your users. This seems like an arbitrary one, that doesn't provide value, to me. My original issue is that I don't have an instance of a class that implements KoinComponent, so have no access to the `inject()` function (for example in a program's `main` function, which has to be outside of any class). 

But I'm just some guy on the internet!

 It's easy enough for me to expose your KoinComponent functions as standalone ones, so I'll just do that.
