### ISSUE TITLE
koinContext has not been initialized

### ISSUE THREAD

**Issue by TedHoryczun** [Ekito/koin#19]
Implemented everything similar to the wiki and got this error:

                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.youtube.tedho.kotlinyoutube/com.youtube.tedho.kotlinyoutube.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property koinContext has not been initialized

**Comment by arnaudgiuliani** [comment]
seems you have not used any starter function. 

Can you give us your code snippet?

**Comment by Baresse** [comment]
Hi @TedHoryczun 

As mentioned by @arnaudgiuliani some code snippet would really help to support you. 
In the mean time you can double check the provided sample app here : [Sample App](https://github.com/Ekito/koin/blob/f2e5c731fc013d1e0e5502112fbf3e115d76c5d2/koin-android/koin-sample-app)

Have a look at the Koin modules definitions in the file [all_modules.kt](https://github.com/Ekito/koin/blob/f2e5c731fc013d1e0e5502112fbf3e115d76c5d2/koin-android/koin-sample-app/src/main/kotlin/org/koin/sampleapp/di/all_modules.kt) and more specifically this line in  [MainApplication.kt](https://github.com/Ekito/koin/blob/f2e5c731fc013d1e0e5502112fbf3e115d76c5d2/koin-android/koin-sample-app/src/main/kotlin/org/koin/sampleapp/MainApplication.kt#L17)  which seems to be what you are missing.

**Comment by nevess** [comment]
Also check of you have the MailApplication.kt register in the Manifest

**Comment by pitoszud** [comment]
In my case the "lateinit property koinContext has not been initialized" exception error happened because of missing android:name=".KoinApp" in the manifest in the <application tag.
The KoinApp extends Application().
It makes sense:

_"The fully qualified name of an Application subclass implemented for the application. When the application process is started, this class is instantiated before any of the application's components."_

https://developer.android.com/guide/topics/manifest/application-element#nm

The question is how to properly try/catch this so the error is more better described.
